services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks: [elknet]

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on: [elasticsearch]
    networks: [elknet]

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
    # DB por defecto (postgres) + init script creará 'airflow' y 'cotopaxi'
    ports:
      - "5432:5432"
    networks: [elknet]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  airflow-webserver:
    image: apache/airflow:2.8.3
    depends_on: [postgres]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      # Vars para tus DAGs
      - ES_URL=http://elasticsearch:9200
      - RT_DIR=/rt_events
      - SEIS_INDEX_PREFIX=seismic_rt
      # Evita problemas de permisos en volúmenes
      - AIRFLOW_UID=50000
    command: >
      bash -lc "pip install --no-cache-dir elasticsearch==7.17.0 &&
                airflow db upgrade &&
                airflow webserver"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /tmp/rt_events:/rt_events
    networks: [elknet]

  airflow-scheduler:
    image: apache/airflow:2.8.3
    depends_on: [postgres]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - ES_URL=http://elasticsearch:9200
      - RT_DIR=/rt_events
      - SEIS_INDEX_PREFIX=seismic_rt
      - AIRFLOW_UID=50000
    command: >
      bash -lc "pip install --no-cache-dir elasticsearch==7.17.0 &&
                airflow db upgrade &&
                airflow scheduler"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /tmp/rt_events:/rt_events
    networks: [elknet]

networks:
  elknet:

volumes:
  pgdata:
