USE cotopaxi;

DROP TABLE IF EXISTS cotopaxi.jefatura_sintetico;

-- Solo dos columnas, como pediste
CREATE TABLE cotopaxi.jefatura_sintetico (
  row_id VARCHAR(16) NOT NULL PRIMARY KEY,
  jefatura_femenina TINYINT(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Genera n = 0 .. 135068 (incluye 0, produce 135,069 filas)
-- Asigna 1 a jefatura_femenina para 1/3 de las filas (n % 3 = 0)
INSERT INTO cotopaxi.jefatura_sintetico (row_id, jefatura_femenina)
SELECT
  CONCAT('Row', n) AS row_id,
  CASE WHEN MOD(n, 3) = 0 THEN 1 ELSE 0 END AS jefatura_femenina
FROM (
  SELECT
    a.n
    + b.n*10
    + c.n*100
    + d.n*1000
    + e.n*10000
    + f.n*100000 AS n
  FROM (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
  CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
  CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
  CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
  CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
  CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) f
) AS seq
WHERE n BETWEEN 0 AND 135068
ORDER BY n;

COMMIT;
